# Generated by Django 4.2.7 on 2025-08-15 19:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(default='mock-usr-001', max_length=100, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('personal_info', models.JSONField(help_text='Stores sensitive user information')),
                ('passport_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('card_info', models.JSONField(help_text='Stores card information')),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('DEBT_USER', 'Debt User')], default='NORMAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['status'], name='users_status_9ca66f_idx'), models.Index(fields=['phone_number'], name='users_phone_n_a3b1c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('response_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'idempotency_keys',
                'indexes': [models.Index(fields=['expires_at'], name='idempotency_expires_6c9d28_idx')],
            },
        ),
        migrations.CreateModel(
            name='BNPLPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bnpl_plans', to='bnpl_service.user')),
            ],
            options={
                'db_table': 'bnpl_plans',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='bnpl_service.user')),
            ],
            options={
                'db_table': 'refunds',
                'indexes': [models.Index(fields=['user', 'status'], name='refunds_user_id_7e4ca0_idx'), models.Index(fields=['transaction_id'], name='refunds_transac_ae9a3c_idx'), models.Index(fields=['status'], name='refunds_status_2569d8_idx'), models.Index(fields=['created_at'], name='refunds_created_7e4196_idx')],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='UPCOMING', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='bnpl_service.bnplplan')),
            ],
            options={
                'db_table': 'installments',
                'ordering': ['due_date'],
                'indexes': [models.Index(fields=['plan', 'status'], name='installment_plan_id_16dbf4_idx'), models.Index(fields=['due_date'], name='installment_due_dat_b37d9a_idx'), models.Index(fields=['status'], name='installment_status_3280a9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='bnplplan',
            index=models.Index(fields=['user', 'status'], name='bnpl_plans_user_id_b99348_idx'),
        ),
        migrations.AddIndex(
            model_name='bnplplan',
            index=models.Index(fields=['created_at'], name='bnpl_plans_created_9c0232_idx'),
        ),
    ]
