# Generated by Django 4.2.7 on 2025-08-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpl_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_info',
            field=models.JSONField(blank=True, help_text='Stores card information', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_info',
            field=models.JSONField(blank=True, help_text='Stores sensitive user information', null=True),
        ),
    ]
