# Generated by Django 4.2.7 on 2025-08-18 09:51

import bnpl_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpl_service', '0002_alter_user_card_info_alter_user_personal_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=bnpl_service.models.generate_user_id, max_length=100, primary_key=True, serialize=False),
        ),
    ]
